<font color=purple > _**Emily Nordhoff - 2022**_ </font>

### Contents:
    1. Importing libraries and data
    2. Data exploration
        2.1 concatenate all dfs
    3. Cleaning
        3.1 remove unnecessary columns
        3.2 mixed-data types
        3.3 outliers
        3.4 missing values
        3.5 duplicates
    4. Export

# Cleaning MLB 2021 balls in play data

## 1. Importing libraries and data

In [1]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns
import scipy

In [2]:
path = r'/Users/Emily/Documents/CF Data Analysis Program/Immersion 6/Hits Analysis/'

In [3]:
df_apr = pd.read_csv(os.path.join(path,'02 data','original data','balls_in_play_mar_apr_2021.csv'),index_col = False)

In [4]:
df_may = pd.read_csv(os.path.join(path,'02 data','original data','balls_in_play_may_2021.csv'),index_col = False)

In [5]:
df_jun = pd.read_csv(os.path.join(path,'02 data','original data','balls_in_play_jun_2021.csv'),index_col = False)

In [6]:
df_jul = pd.read_csv(os.path.join(path,'02 data','original data','balls_in_play_jul_2021.csv'),index_col = False)

In [7]:
df_aug = pd.read_csv(os.path.join(path,'02 data','original data','balls_in_play_aug_2021.csv'),index_col = False)

In [8]:
df_sep = pd.read_csv(os.path.join(path,'02 data','original data','balls_in_play_sep_oct_2021.csv'),index_col = False)

## 2. Data exploration

In [9]:
print(df_apr.shape, '\n')
print(df_may.shape, '\n')
print(df_jun.shape, '\n')
print(df_jul.shape, '\n')
print(df_aug.shape, '\n')
print(df_sep.shape)

(18566, 92)

(20489, 92)

(19903, 92)

(18723, 92)

(21162, 92)

(22864, 92)

### 2.1 Concatenate all dfs & then explore

In [29]:
df = pd.concat([df_apr,
                df_may,
                df_jun,
                df_jul,
                df_aug,
                df_sep])

In [30]:
df.shape

(121707, 92)

In [31]:
df.info(verbose=False)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 121707 entries, 0 to 22863
Columns: 92 entries, pitch_type to delta_run_exp
dtypes: float64(45), int64(30), object(17)
memory usage: 86.4+ MB

In [32]:
df.columns.tolist()

['pitch_type',
 'game_date',
 'release_speed',
 'release_pos_x',
 'release_pos_z',
 'player_name',
 'batter',
 'pitcher',
 'events',
 'description',
 'spin_dir',
 'spin_rate_deprecated',
 'break_angle_deprecated',
 'break_length_deprecated',
 'zone',
 'des',
 'game_type',
 'stand',
 'p_throws',
 'home_team',
 'away_team',
 'type',
 'hit_location',
 'bb_type',
 'balls',
 'strikes',
 'game_year',
 'pfx_x',
 'pfx_z',
 'plate_x',
 'plate_z',
 'on_3b',
 'on_2b',
 'on_1b',
 'outs_when_up',
 'inning',
 'inning_topbot',
 'hc_x',
 'hc_y',
 'tfs_deprecated',
 'tfs_zulu_deprecated',
 'fielder_2',
 'umpire',
 'sv_id',
 'vx0',
 'vy0',
 'vz0',
 'ax',
 'ay',
 'az',
 'sz_top',
 'sz_bot',
 'hit_distance_sc',
 'launch_speed',
 'launch_angle',
 'effective_speed',
 'release_spin_rate',
 'release_extension',
 'game_pk',
 'pitcher.1',
 'fielder_2.1',
 'fielder_3',
 'fielder_4',
 'fielder_5',
 'fielder_6',
 'fielder_7',
 'fielder_8',
 'fielder_9',
 'release_pos_y',
 'estimated_ba_using_speedangle',
 'estimated_woba_using_speedangle',
 'woba_value',
 'woba_denom',
 'babip_value',
 'iso_value',
 'launch_speed_angle',
 'at_bat_number',
 'pitch_number',
 'pitch_name',
 'home_score',
 'away_score',
 'bat_score',
 'fld_score',
 'post_away_score',
 'post_home_score',
 'post_bat_score',
 'post_fld_score',
 'if_fielding_alignment',
 'of_fielding_alignment',
 'spin_axis',
 'delta_home_win_exp',
 'delta_run_exp']

## 3. Cleaning

### 3.1 Remove unnecessary columns

In [33]:
# a list of all the useless columns
no_need = ['spin_dir',
          'spin_rate_deprecated',
          'break_angle_deprecated',
          'break_length_deprecated',
          'des',
          'description',
          'game_type',
          'game_year', 
          'type',
          'hc_x','hc_y',
          'tfs_deprecated',
          'tfs_zulu_deprecated',
          'umpire',
          'sz_top', 'sz_bot',
          'effective_speed',
          'release_extension',
          'pitcher.1',
          'fielder_2.1', 'fielder_2',
          'fielder_3', 'fielder_4', 'fielder_5', 'fielder_6',
          'fielder_7', 'fielder_8', 'fielder_9',
          'release_pos_y',
          'estimated_ba_using_speedangle',
          'estimated_woba_using_speedangle',
          'woba_value',
          'woba_denom',
          'babip_value',
          'iso_value','delta_home_win_exp','delta_run_exp',
          'sv_id',
          'balls', 
          'strikes',
          'outs_when_up']

In [34]:
# drop the columns listed above

df.drop(columns=no_need, inplace=True)

In [35]:
df.shape

(121707, 51)

In [36]:
df.info(verbose=False)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 121707 entries, 0 to 22863
Columns: 51 entries, pitch_type to spin_axis
dtypes: float64(24), int64(14), object(13)
memory usage: 48.3+ MB

### 3.2 Mixed data types

In [37]:
# Check for mixed-type data
# this prints out the columns that have mixed types

mixed_col = []
for col in df.columns.tolist():
  weird = (df[[col]].applymap(type) != df[[col]].iloc[0].apply(type)).any(axis = 1)
  if len (df[weird]) > 0:
    print (col)
    mixed_col.append(col)

pitch_type
bb_type
pitch_name
if_fielding_alignment
of_fielding_alignment

In [38]:
# Value_counts for all the columns with mixed type to check if it's because of NaN values

for value in mixed_col:
    print(df[value].value_counts(dropna=False), '\n')

FF     40617
SI     22150
SL     21636
CH     15909
FC      8883
CU      8218
KC      2122
FS      1849
FA       210
NaN       53
CS        28
EP        16
KN        15
SC         1
Name: pitch_type, dtype: int64

ground_ball    53417
fly_ball       31195
line_drive     28720
popup           8371
NaN                4
Name: bb_type, dtype: int64

4-Seam Fastball    40617
Sinker             22150
Slider             21636
Changeup           15909
Cutter              8883
Curveball           8246
Knuckle Curve       2122
Split-Finger        1849
Fastball             210
NaN                   53
Eephus                16
Knuckleball           15
Screwball              1
Name: pitch_name, dtype: int64

Standard         74479
Infield shift    36266
Strategic        10355
NaN                607
Name: if_fielding_alignment, dtype: int64

Standard          111975
Strategic           8954
NaN                  607
4th outfielder       171
Name: of_fielding_alignment, dtype: int64

In [39]:
# each of these columns have string/object data mixed with NaN
# I am not going to do anything

### 3.3 Outliers

In [40]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
release_speed,121653.0,88.906001,5.969904,30.100000,84.800000,89.900000,93.600000,102.500000
release_pos_x,121619.0,-0.681344,1.895438,-4.630000,-2.050000,-1.410000,1.300000,4.480000
release_pos_z,121619.0,5.853369,0.543007,1.000000,5.610000,5.890000,6.180000,7.730000
batter,121707.0,598412.227349,63001.341406,405395.000000,553902.000000,607732.000000,650490.000000,685503.000000
pitcher,121707.0,598318.805492,64626.364922,424144.000000,570632.000000,608335.000000,656288.000000,685503.000000
zone,121654.0,6.844362,3.611288,1.000000,4.000000,6.000000,9.000000,14.000000
hit_location,115340.0,6.169560,2.189370,1.000000,5.000000,7.000000,8.000000,9.000000
pfx_x,121654.0,-0.124355,0.881634,-2.310000,-0.890000,-0.200000,0.590000,2.400000
pfx_z,121654.0,0.661830,0.703157,-2.130000,0.240000,0.760000,1.230000,2.430000
plate_x,121654.0,0.003416,0.545184,-2.080000,-0.380000,0.000000,0.390000,2.390000
plate_z,121654.0,2.352171,0.573845,-0.640000,1.950000,2.340000,2.740000,5.030000
on_3b,11946.0,600536.947179,61770.756003,405395.000000,570731.000000,608333.500000,656555.000000,683734.000000
on_2b,23383.0,600321.425608,62007.401787,405395.000000,570731.000000,608336.000000,656541.000000,683734.000000
on_1b,38262.0,598917.297580,63013.222767,405395.000000,553993.000000,608070.000000,656305.000000,683734.000000
inning,121707.0,4.886506,2.565878,1.000000,3.000000,5.000000,7.000000,16.000000
vx0,121654.0,2.000432,5.687787,-16.608454,-3.319517,3.858740,6.284122,16.162399
vy0,121654.0,-129.331544,8.640023,-148.992834,-136.171548,-130.831788,-123.499906,-40.422498
vz0,121654.0,-3.954619,2.756993,-13.125103,-5.811199,-4.134650,-2.342319,13.967712
ax,121654.0,-2.196170,10.813432,-29.574151,-11.454314,-2.405960,6.241466,29.761284
ay,121654.0,26.551682,3.927051,3.249950,23.630807,26.532128,29.443482,44.329768
az,121654.0,-23.350595,8.577491,-51.271290,-29.279522,-22.916086,-16.058792,-3.089565
hit_distance_sc,121325.0,163.671189,137.048367,0.000000,18.000000,152.000000,288.000000,495.000000
launch_speed,121327.0,88.061548,15.361620,7.100000,79.600000,91.100000,99.400000,122.200000
launch_angle,121324.0,12.038385,29.242714,-89.000000,-6.000000,13.000000,31.000000,90.000000
release_spin_rate,121214.0,2206.038923,336.627095,43.000000,2044.000000,2229.000000,2406.000000,3722.000000
game_pk,121707.0,633403.064154,715.411012,632169.000000,632782.000000,633380.000000,634035.000000,634656.000000
launch_speed_angle,121321.0,3.186110,1.296495,1.000000,2.000000,3.000000,4.000000,6.000000
at_bat_number,121707.0,38.073619,22.299815,1.000000,19.000000,37.000000,56.000000,125.000000
pitch_number,121707.0,3.378894,1.835323,1.000000,2.000000,3.000000,5.000000,16.000000
home_score,121707.0,2.228459,2.611560,0.000000,0.000000,1.000000,3.000000,22.000000
away_score,121707.0,2.304921,2.636700,0.000000,0.000000,2.000000,4.000000,24.000000
bat_score,121707.0,2.261834,2.588809,0.000000,0.000000,1.000000,3.000000,24.000000
fld_score,121707.0,2.271546,2.659583,0.000000,0.000000,1.000000,3.000000,24.000000
post_away_score,121707.0,2.390298,2.669557,0.000000,0.000000,2.000000,4.000000,24.000000
post_home_score,121707.0,2.316662,2.649243,0.000000,0.000000,2.000000,4.000000,22.000000
post_bat_score,121707.0,2.435415,2.657240,0.000000,0.000000,2.000000,4.000000,24.000000
post_fld_score,121707.0,2.271546,2.659583,0.000000,0.000000,1.000000,3.000000,24.000000
spin_axis,121215.0,177.246133,67.548295,0.000000,136.000000,199.000000,221.000000,360.000000

In [41]:
# Nothing looks particularly high or low here.
# There are some NaNs, which is seen in the count

### 3.4 Missing values

In [42]:
# Aggregrate missing values for all columns

df.isnull().sum()

pitch_type                   53
game_date                     0
release_speed                54
release_pos_x                88
release_pos_z                88
player_name                   0
batter                        0
pitcher                       0
events                        0
zone                         53
stand                         0
p_throws                      0
home_team                     0
away_team                     0
hit_location               6367
bb_type                       4
pfx_x                        53
pfx_z                        53
plate_x                      53
plate_z                      53
on_3b                    109761
on_2b                     98324
on_1b                     83445
inning                        0
inning_topbot                 0
vx0                          53
vy0                          53
vz0                          53
ax                           53
ay                           53
az                           53
hit_distance_sc             382
launch_speed                380
launch_angle                383
release_spin_rate           493
game_pk                       0
launch_speed_angle          386
at_bat_number                 0
pitch_number                  0
pitch_name                   53
home_score                    0
away_score                    0
bat_score                     0
fld_score                     0
post_away_score               0
post_home_score               0
post_bat_score                0
post_fld_score                0
if_fielding_alignment       607
of_fielding_alignment       607
spin_axis                   492
dtype: int64

In [43]:
# There are a number of variables that have NaN for exactly 53 records. Investigate!

df[df['pitch_type'].isnull()]

,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,batter,pitcher,events,zone,...,away_score,bat_score,fld_score,post_away_score,post_home_score,post_bat_score,post_fld_score,if_fielding_alignment,of_fielding_alignment,spin_axis
6314,NaN,2021-08-22,NaN,NaN,NaN,"Stassi, Max",545358,615698,force_out,NaN,...,0,0,0,0,0,0,0,NaN,NaN,NaN
6325,NaN,2021-08-22,NaN,NaN,NaN,"Walsh, Jared",665120,615698,field_out,NaN,...,0,0,0,0,0,0,0,NaN,NaN,NaN
6496,NaN,2021-08-22,NaN,NaN,NaN,"Fletcher, David",664058,615698,field_out,NaN,...,0,0,0,0,0,0,0,NaN,NaN,NaN
6501,NaN,2021-08-22,NaN,NaN,NaN,"Rosario, Amed",642708,518553,field_out,NaN,...,0,3,0,0,3,3,0,NaN,NaN,NaN
6522,NaN,2021-08-22,NaN,NaN,NaN,"Ohtani, Shohei",660271,615698,single,NaN,...,0,0,0,0,0,0,0,NaN,NaN,NaN
6530,NaN,2021-08-22,NaN,NaN,NaN,"Ramírez, José",608070,660761,field_out,NaN,...,0,2,0,0,2,2,0,NaN,NaN,NaN
6564,NaN,2021-08-22,NaN,NaN,NaN,"Rosario, Amed",642708,660761,home_run,NaN,...,0,0,0,0,2,2,0,NaN,NaN,NaN
6626,NaN,2021-08-22,NaN,NaN,NaN,"Straw, Myles",664702,660761,double,NaN,...,0,0,0,0,0,0,0,NaN,NaN,NaN
13028,NaN,2021-08-12,NaN,NaN,NaN,"Judge, Aaron",592450,458681,field_error,NaN,...,4,4,7,4,7,4,7,NaN,NaN,NaN
13033,NaN,2021-08-12,NaN,NaN,NaN,"Gardner, Brett",458731,458681,home_run,NaN,...,3,3,7,4,7,4,7,NaN,NaN,NaN
13036,NaN,2021-08-12,NaN,NaN,NaN,"LeMahieu, DJ",518934,458681,field_out,NaN,...,3,3,7,3,7,3,7,NaN,NaN,NaN
13057,NaN,2021-08-12,NaN,NaN,NaN,"Odor, Rougned",596059,458681,field_out,NaN,...,3,3,5,3,5,3,5,NaN,NaN,NaN
13071,NaN,2021-08-12,NaN,NaN,NaN,"Moncada, Yoán",660162,571760,force_out,NaN,...,3,7,3,3,7,7,3,NaN,NaN,NaN
13078,NaN,2021-08-12,NaN,NaN,NaN,"Jiménez, Eloy",650391,571760,field_out,NaN,...,3,7,3,3,7,7,3,NaN,NaN,NaN
13084,NaN,2021-08-12,NaN,NaN,NaN,"Voit, Luke",572228,458681,field_out,NaN,...,3,3,5,3,5,3,5,NaN,NaN,NaN
13085,NaN,2021-08-12,NaN,NaN,NaN,"Stanton, Giancarlo",519317,458681,field_out,NaN,...,3,3,5,3,5,3,5,NaN,NaN,NaN
13106,NaN,2021-08-12,NaN,NaN,NaN,"Hernández, César",514917,571760,field_out,NaN,...,3,7,3,3,7,7,3,NaN,NaN,NaN
13124,NaN,2021-08-12,NaN,NaN,NaN,"Anderson, Tim",641313,571760,field_out,NaN,...,3,7,3,3,7,7,3,NaN,NaN,NaN
13127,NaN,2021-08-12,NaN,NaN,NaN,"Judge, Aaron",592450,458681,home_run,NaN,...,0,0,1,3,1,3,1,NaN,NaN,NaN
13145,NaN,2021-08-12,NaN,NaN,NaN,"Gardner, Brett",458731,458681,single,NaN,...,0,0,1,0,1,0,1,NaN,NaN,NaN
13149,NaN,2021-08-12,NaN,NaN,NaN,"Zavala, Seby",664874,571760,home_run,NaN,...,3,5,3,3,7,7,3,NaN,NaN,NaN
13151,NaN,2021-08-12,NaN,NaN,NaN,"Engel, Adam",641553,571760,field_out,NaN,...,3,5,3,3,5,5,3,NaN,NaN,NaN
13161,NaN,2021-08-12,NaN,NaN,NaN,"Robert, Luis",673357,571760,double,NaN,...,3,5,3,3,5,5,3,NaN,NaN,NaN
13170,NaN,2021-08-12,NaN,NaN,NaN,"Vaughn, Andrew",683734,571760,field_out,NaN,...,3,5,3,3,5,5,3,NaN,NaN,NaN
13190,NaN,2021-08-12,NaN,NaN,NaN,"Wade, Tyler",642180,458681,field_out,NaN,...,0,0,1,0,1,0,1,NaN,NaN,NaN
13195,NaN,2021-08-12,NaN,NaN,NaN,"Moncada, Yoán",660162,571760,field_out,NaN,...,3,5,3,3,5,5,3,NaN,NaN,NaN
13215,NaN,2021-08-12,NaN,NaN,NaN,"Jiménez, Eloy",650391,571760,home_run,NaN,...,3,2,3,3,5,5,3,NaN,NaN,NaN
13227,NaN,2021-08-12,NaN,NaN,NaN,"Higashioka, Kyle",543309,458681,field_out,NaN,...,0,0,1,0,1,0,1,NaN,NaN,NaN
13265,NaN,2021-08-12,NaN,NaN,NaN,"Odor, Rougned",596059,458681,field_out,NaN,...,0,0,1,0,1,0,1,NaN,NaN,NaN
13275,NaN,2021-08-12,NaN,NaN,NaN,"Anderson, Tim",641313,571760,double,NaN,...,3,1,3,3,2,2,3,NaN,NaN,NaN
13350,NaN,2021-08-12,NaN,NaN,NaN,"Robert, Luis",673357,571760,field_out,NaN,...,0,1,0,0,1,1,0,NaN,NaN,NaN
13355,NaN,2021-08-12,NaN,NaN,NaN,"Gallo, Joey",608336,458681,field_out,NaN,...,0,0,0,0,0,0,0,NaN,NaN,NaN
13404,NaN,2021-08-12,NaN,NaN,NaN,"Wade, Tyler",642180,656629,single,NaN,...,4,4,7,4,7,4,7,NaN,NaN,NaN
13416,NaN,2021-08-12,NaN,NaN,NaN,"Stanton, Giancarlo",519317,521230,home_run,NaN,...,6,6,7,8,7,8,7,NaN,NaN,NaN
13430,NaN,2021-08-12,NaN,NaN,NaN,"Anderson, Tim",641313,593974,field_out,NaN,...,4,7,4,4,7,7,4,NaN,NaN,NaN
13455,NaN,2021-08-12,NaN,NaN,NaN,"Higashioka, Kyle",543309,656629,field_out,NaN,...,4,4,7,4,7,4,7,NaN,NaN,NaN
13491,NaN,2021-08-12,NaN,NaN,NaN,"Judge, Aaron",592450,521230,home_run,NaN,...,4,4,7,6,7,6,7,NaN,NaN,NaN
13510,NaN,2021-08-12,NaN,NaN,NaN,"Jiménez, Eloy",650391,571760,field_out,NaN,...,0,1,0,0,1,1,0,NaN,NaN,NaN
13511,NaN,2021-08-12,NaN,NaN,NaN,"Engel, Adam",641553,593974,field_out,NaN,...,4,7,4,4,7,7,4,NaN,NaN,NaN
13532,NaN,2021-08-12,NaN,NaN,NaN,"Vaughn, Andrew",683734,570257,single,NaN,...,4,7,4,4,7,7,4,NaN,NaN,NaN
13535,NaN,2021-08-12,NaN,NaN,NaN,"Anderson, Tim",641313,502154,home_run,NaN,...,8,7,8,8,9,9,8,NaN,NaN,NaN
13549,NaN,2021-08-12,NaN,NaN,NaN,"Gallo, Joey",608336,607481,force_out,NaN,...,4,4,7,4,7,4,7,NaN,NaN,NaN
13553,NaN,2021-08-12,NaN,NaN,NaN,"Abreu, José",547989,571760,home_run,NaN,...,0,0,0,0,1,1,0,NaN,NaN,NaN
13568,NaN,2021-08-12,NaN,NaN,NaN,"LeMahieu, DJ",518934,458681,single,NaN,...,0,0,0,0,0,0,0,NaN,NaN,NaN
13583,NaN,2021-08-12,NaN,NaN,NaN,"Robert, Luis",673357,593974,force_out,NaN,...,4,7,4,4,7,7,4,NaN,NaN,NaN
13611,NaN,2021-08-12,NaN,NaN,NaN,"Moncada, Yoán",660162,570257,double_play,NaN,...,4,7,4,4,7,7,4,NaN,NaN,NaN
13625,NaN,2021-08-12,NaN,NaN,NaN,"Stanton, Giancarlo",519317,518886,field_out,NaN,...,4,4,7,4,7,4,7,NaN,NaN,NaN
13626,NaN,2021-08-12,NaN,NaN,NaN,"Stanton, Giancarlo",519317,656629,field_out,NaN,...,4,4,7,4,7,4,7,NaN,NaN,NaN
13670,NaN,2021-08-12,NaN,NaN,NaN,"Gardner, Brett",458731,607481,force_out,NaN,...,4,4,7,4,7,4,7,NaN,NaN,NaN
13671,NaN,2021-08-12,NaN,NaN,NaN,"Jiménez, Eloy",650391,570257,single,NaN,...,4,7,4,4,7,7,4,NaN,NaN,NaN
13693,NaN,2021-08-12,NaN,NaN,NaN,"Mendick, Danny",664901,502154,field_out,NaN,...,8,7,8,8,7,7,8,NaN,NaN,NaN
13696,NaN,2021-08-12,NaN,NaN,NaN,"Anderson, Tim",641313,571760,field_out,NaN,...,0,0,0,0,0,0,0,NaN,NaN,NaN
13707,NaN,2021-08-12,NaN,NaN,NaN,"Wade, Tyler",642180,521230,single,NaN,...,4,4,7,4,7,4,7,NaN,NaN,NaN

In [44]:
# There are 53 records that don't have any measured data besides the result of the plate appearance
# I will leave these in for now, but miht filter them out for analysis

In [45]:
df[df['hit_location'].isnull()]['events'].value_counts()

home_run           5933
double              430
single                3
fielders_choice       1
Name: events, dtype: int64

In [46]:
# Hit_location is the position of which fielder touches the ball first.
# by definition, no fielder will touch a home run ball

In [47]:
# Number of null values fron 'release_spin_rate' divided by the number of records

round(493/121707*100,2)

0.41

In [48]:
# With Hawk-Eye, Statcast claims to be able to track 99% of all batted balls
# The measured variable with the highest number of null values ('release_spin_rate')
# is missing 493 values. That only amounts to 0.41% of all batted balls
# so, this is an acceptable amount of missing values.
# I will leave all records in place for now, because we can still look at the
# categorical aspects of the records without the measured data.
# Then, those records can be filtered out later.

### 3.5 Duplicates

In [49]:
# check for exact duplicates

df[df.duplicated()]

Empty DataFrame
Columns: [pitch_type, game_date, release_speed, release_pos_x, release_pos_z, player_name, batter, pitcher, events, zone, stand, p_throws, home_team, away_team, hit_location, bb_type, pfx_x, pfx_z, plate_x, plate_z, on_3b, on_2b, on_1b, inning, inning_topbot, vx0, vy0, vz0, ax, ay, az, hit_distance_sc, launch_speed, launch_angle, release_spin_rate, game_pk, launch_speed_angle, at_bat_number, pitch_number, pitch_name, home_score, away_score, bat_score, fld_score, post_away_score, post_home_score, post_bat_score, post_fld_score, if_fielding_alignment, of_fielding_alignment, spin_axis]
Index: []

[0 rows x 51 columns]

In [50]:
# YAY no full duplicates & no other keys to check

## 4. Export

In [51]:
#df.to_csv(os.path.join(path, '02 data', 'prepared data', 'balls_in_play_2021_clean.csv'))

In [52]:
#df.to_pickle(os.path.join(path, '02 data', 'prepared data', 'balls_in_play_2021_clean.pkl'))

In [56]:
df.to_csv(os.path.join(path, '02 data', 'prepared data', 'bip_clean.csv'))